### PR TITLE
WIP: Support for non-square inputs and kernels

### PR DESCRIPTION
**Pull request by SpontaneousDuck**
I am working on adding a support for non-square images and kernels. I think all that needs to happen for this is modifications to the slidingwindow unit. I will be working on this through a separate file so as to not break the original SWU. Please let me know if there is anything else that needs to change for this to work. I will add some test benches soon as well.

### CODE REVIEW

**Comment by giuliogamba** [comment]
Hi @SpontaneousDuck, that's a good idea to put the non-square SWG on a different file, and please use as a reference for the testbench the project [here](https://github.com/Xilinx/finn-hlslib/blob/master/tb/swg_tb.cpp). I believe changing the SWG unit should be enough for non-square conv layer support.

**Comment by giuliogamba** [comment]
@SpontaneousDuck Do you have any update about this?

**Comment by SpontaneousDuck** [comment]
@giuliogamba Sorry about the long time away. I got pulled away for another project unfortunately, but I am finally at the point where I am working on my code again. The commits I made here should work and I verified the code in python. I think all that is left for me to do is verify this code actually works as written in C++ as well as write a test bench for it. I am starting to work on my model again today so I will be actively working on this over the next two weeks most likely.

**Comment by giuliogamba** [comment]
Hi, the non-square support to images/kernel/stride has been added in #33. Can you please check it this works for you.

**Pull request closed without merging**
