### PR TITLE
Add UpsamplingNearest layer

### PR DESCRIPTION
**Pull request by erlingrj**
This PR adds a simple Upsampling layer with the Nearest Neighbor algorithm. It has no configuration parameters that the FINN compiler can tune. It reads C pixels each clock cycle from the input stream and duplicates thos pixels according to the scale factor. It also buffers each input row internally so it can duplicate also the rows. When the scale factor is not an integer it pads according to have PyTorch does it.

I gladly accept feedback on code structure, I am completely new to HLS and not yet sure of the compiler understands my intent. Functionally it should be correct (verified with C-sim and co-sim).

### CODE REVIEW

**Comment by giuliogamba** [comment]
Hi @erlingrj, thanks for the contribution! Can I ask you if you can add a function (suggested name `UpsampleNearest_Batch` to keep the naming conventions) which is able to run with multiple images (thus having the additional `numReps` parameter)?

**Comment by erlingrj** [comment]
I will add UpsampleNearest_Batch. Regarding the pipelining I will try to add the HLS prgram for unrolling. I tried to express the design in a dataflow manner which would naturally be "unrolled" if it was implemented in RTL. I was a bit confused by the schedules generated by Vitis HLS so it might be that my intent was not caught by the compiler, I will try adding unroll pragmas with II=1. Thanks for the feedback

**Comment by giuliogamba** [comment]
That's fair, I do believe you will be able to get the desired II if you don't use an `hls::stream` to buffer the row (using instead directly an array) and if you inline the function `UpsampleNearestGenerateOutputRow` inside the `UpsampleNearest` call. Let me know if you want to have a more detailed discussions (you can tag me on [gitter](https://gitter.im/xilinx-finn/community))

**Comment by giuliogamba** [comment]
Hi @erlingrj, do you have an update about this? Let me know if you need any help!

**Pull request merged**
